services:
  zabbix-server:
    hostname: zabbix-server
    container_name: zabbix-server
    restart: unless-stopped
    image: zabbix/zabbix-server-pgsql:alpine-${ZABBIX_VERSION}
    user: "33:116"
    ports: 
      - "10051:10051"
    environment:
      - DB_SERVER_PORT=5432
      - DB_SERVER_HOST=timescaledb
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=T@uris2025
      - ENABLE_TIMESCALEDB=true
      - ZBX_STARTREPORTWRITERS=2
      - ZBX_WEBSERVICEURL=http://zabbix-reports:10053/report
    volumes:
      - /zabbixvol/server:/var/lib/zabbix
      - ./zabbix/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
    depends_on:
      - timescaledb
    healthcheck:
      test: ["CMD", "zabbix_server", "-V"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - network-zabbix
    labels:
      com.zabbix.description: "Zabbix server with PostgreSQL database support"
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "zabbix-server"
      com.zabbix.dbtype: "pgsql"
      com.zabbix.os: "alpine"

  zabbix-frontend:
    hostname: zabbix-frontend
    restart: unless-stopped
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-apache-pgsql:alpine-${ZABBIX_VERSION}
    environment:
      - DB_SERVER_PORT=5432
      - DB_SERVER_HOST=timescaledb
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=T@uris2025
      - PHP_TZ=Europe/Bratislava
      - ZBX_SERVER_NAME=zabbix-server
      - ZBX_SERVER_HOST=zabbix-server
      - APACHE_RUN_USER=#33
      - APACHE_RUNGROUP=#116
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./zabbix/etc/ssl/apache2:/etc/ssl/apache2:ro
        #      - /zabbixvol/web:/usr/share/zabbix
    depends_on:
      - timescaledb
      - zabbix-server
    ports:
      - "8099:8080"
      - "9443:8443"
    networks:
      - network-zabbix
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/index.php"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  zabbix-agent:
    hostname: zabbix-agent
    restart: unless-stopped
    image: zabbix/zabbix-agent2:alpine-${ZABBIX_VERSION}
    container_name: zabbix-agent
    user: "33:116"
    ports: 
      - "10050:10050"
    environment:
      - ZBX_HOSTNAME=zabbix-agent
      - ZBX_SERVER_HOST=zabbix-server
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./zabbix/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
      - ./zabbix/frontend_hacks:/usr/share/zabbix/local/
      - /zabbixvol/agent:/var/lib/zabbix
    networks:
      - network-zabbix
    depends_on:
      - zabbix-server

  timescaledb:
    hostname: timescaledb
    container_name: timescaledb
    restart: unless-stopped
    image: timescale/timescaledb:2.19.1-pg17-oss
    user: "33:116"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=T@uris2025
      - TS_TUNE_MEMORY=2GB
      - TS_TUNE_NUM_CPUS=2
    networks:
      - network-zabbix
    volumes:
      - /zabbixvol/timescaledb:/var/lib/postgresql/data
    command: ["postgres", "-c", "max_connections=100"]

  zabbix-reports:
    hostname: zabbix-reports
    container_name: zabbix-reports
    restart: unless-stopped
    image: zabbix/zabbix-web-service:alpine-${ZABBIX_VERSION}
    user: "33:116"
    environment:
      - ZBX_ALLOWEDIP=zabbix-server,zabbix-frontend
    cap_add:
      - SYS_ADMIN
    networks:
      - network-zabbix
    depends_on:
      - zabbix-server
      - zabbix-frontend

  grafana:
    hostname: grafana
    container_name: grafana
    restart: unless-stopped
    image: grafana/grafana:${GRAFANA_VERSION}
    environment:
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app ${GFN_ZBX_PLUGIN_VERSION}
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=alexanderzobnin-zabbix-datasource
      - GF_LOG_LEVEL=debug
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=mailhog:1025
      - GF_SMTP_USER=
      - GF_SMTP_PASSWORD=
      - GF_SMTP_CERT_FILE=
      - GF_SMTP_KEY_FILE=
      - GF_SMTP_EHLO_IDENTITY=
      - GF_SMTP_SKIP_VERIFY=false
      - GF_SMTP_FROM_ADDRESS=grafana@zabbixlab.local
      - GF_SMTP_NAME=Grafana-Tauris
    volumes:
      - /zabbixvol/grafana:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3010:3000"
    networks:
      - network-zabbix
    depends_on:
      - zabbix-frontend

  zapix:
    hostname: zapix
    container_name: zapix
    restart: unless-stopped
    build:
      context: ./zapix
    networks:
      - network-zabbix
    depends_on:
      - zabbix-frontend

  pgadmin:
    hostname: pgadmin
    container_name: pgadmin
    restart: unless-stopped
    user: "33:116"
    image: thajeztah/pgadmin4
    networks:
      - network-zabbix
    volumes:
      - /zabbixvol/pgadmin:/pgadmin
    depends_on:
      - timescaledb

  mailhog:
    hostname: mailhog
    container_name: mailhog
    restart: unless-stopped
    image: mailhog/mailhog:v1.0.0
    environment:
      - MH_HOSTNAME=mailhog

  zabbix-provisioning:
    hostname: zabbix-provisioning
    container_name: zabbix-provisioning
    image: python:3.9-alpine3.22
    command: ["python", "/tmp/provisioning.py"]
    volumes:
      - ./zabbix/provisioning.py:/tmp/provisioning.py:ro
    networks:
      - network-zabbix
    depends_on:
      - zabbix-frontend

networks:
  network-zabbix:
    driver: bridge
